accounts/urls.py
from . import views
from django.urls import path

app_name = 'accounts'

urlpatterns = [
    path('signup/',views.signup_view,name='signup'),
    path('login/',views.login_view,name='login'),
    path('logout/',views.logout_view,name='logout'),
]

fronted/urls.py
from urllib.parse import urlparse
from django.urls import path
from . import views

app_name='fronted'

urlpatterns = [
    # path('',views.home,name='home')#when someone ask for domain name/ we pass view.home
    path('',views.HomeView.as_view(),name='home'),
    path('product/<slug>/',views.ProductDetailView.as_view(),name='detail'),
    # path('test/',views.testpage,name='test')
    path('add-to-cart/<slug>/',views.add_to_cart,name='add-to-cart')
]

mainapp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns #to include image
from django.conf.urls.static import static
from django.conf import settings
#other imoprts
#from django.urls import include

urlpatterns = [
    path('admin/', admin.site.urls), #already defined path for django admin side
    path('',include('fronted.urls')),
    path('accounts/',include('accounts.urls')),
]

urlpatterns +=staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL,document_root = settings.MEDIA_ROOT)




accounts/models.py
from django.db import models

# Create your models here.

fronted/models.py
from unicodedata import category
from django.db import models
from django.shortcuts import reverse
from django_countries.fields import CountryField

from django.contrib.auth.models import User

# Create your models here.
CATEGORY_CHOICES=(
    ('C','Computer'),
    ('M','Mobile'),
    ('T','Tablet')
)
LABEL_CHOICES=(
    ('N','New'),
    ('R','Refirbished'),
    ('U','Used')
)
class Item(models.Model):
    title=models.CharField(max_length=100)
    price=models.FloatField()
    discount_price= models.FloatField(blank=True,null=True)
    category=models.CharField(choices=CATEGORY_CHOICES,max_length=5)
    label=models.CharField(choices=LABEL_CHOICES,max_length=5)
    slug=models.SlugField() #read its benfits instead of id
    description=models.TextField()
    image=models.ImageField() #check pillow

    def __str__(self): #in admin side whenever we save it save by its title
        return self.title
    def get_discount_percent(self):
        discount_percent = 100 - (self.discount_price*100/self.price)
        return discount_percent
    
    def get_item_url(self):
        return reverse('fronted:detail' , kwargs={'slug':self.slug})

class OrderItem(models.Model):
    user=models.ForeignKey(User, on_delete=models.CASCADE)
    ordered=models.BooleanField(default=False)
    item=models.ForeignKey(Item, on_delete=models.CASCADE)
    quantity=models.IntegerField(default=1)

    def __str__(self):
        return f"{self.quantity}-{self.item.title}"

class Order(models.Model):
    user=models.ForeignKey(User, on_delete=models.CASCADE) #settings.AUTH_USER_MODEL
    order_ref=models.CharField(max_length=20)
    items=models.ManyToManyField(OrderItem)
    ordered_date=models.DateField()
    ordered=models.BooleanField(default=False)
    billing_address=models.ForeignKey('BillingAddress',on_delete=models.SET_NULL,blank=True,null=True)
    coupon=models.ForeignKey('Coupon',on_delete=models.SET_NULL,blank=True,null=True)
    payment=models.ForeignKey('Payment',on_delete=models.SET_NULL,blank=True,null=True)
    delivered=models.BooleanField(default=False)
    received=models.BooleanField(default=False)
    refund_requested=models.BooleanField(default=False)
    refund_granted=models.BooleanField(default=False)

    def __str__(self):
        return self.user.username

class BillingAddress(models.Model):
    user=models.ForeignKey(User,on_delete=models.CASCADE)
    street_address=models.CharField(max_length=100)
    apartment=models.CharField(max_length=100)
    country = CountryField(max_length=100)
    zip=models.CharField(max_length=10)

    def __str__(self):
        return self.user.username

class Coupon(models.Model):
    code=models.CharField(max_length=20)
    amount=models.FloatField()

    def __str__(self):
        return self.code

class Payment(models.Model):
    stripe_charge_id=models.CharField(max_length=100)
    user=models.ForeignKey(User,on_delete=models.SET_NULL,blank=True,null=True)
    amount=models.FloatField()
    timestamp=models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.user.name #self.user.username

class Refund(models.Model):
    order=models.ForeignKey(Order,on_delete=models.CASCADE)
    reason=models.TextField()
    accepted=models.BooleanField(default=False)

    def __str__(self):
        return f"{self.pk}"

accounts/views.py
from django.shortcuts import render,redirect

# Create your views here.
from django.contrib.auth.forms import UserCreationForm,AuthenticationForm
from django.contrib.auth import logout, login

def signup_view(request):
    if request.method=='POST':
        form=UserCreationForm(request.POST)
        if form.is_valid():
            user=form.save()#we save as well as get data
            login(request,user)
            return redirect('fronted:home')
        else:
            form=UserCreationForm()
            return render(request,'signup.html',{'form':form})
    else:
        form =UserCreationForm(request.POST)
    
    return render(request,'signup.html',{'form':form})

def login_view(request):
    if request.method=='POST':
        signin_form=AuthenticationForm(data=request.POST)
        if signin_form.is_valid():
            user=signin_form.get_user()
            login(request,user)

            if 'next' in request.POST:
                return redirect(request.POST.get('next'))
            else:
                return redirect('fronted:home')
    else:
        signin_form=AuthenticationForm()
    return render(request,'login.html',{'signin_form':signin_form})#we are sending this as response to request

def logout_view(request):
    if request.method=='POST':
        logout(request)
        return redirect('fronted:home')
    else:
        logout(request)
    return redirect('fronted:home')

fronted/views.py
from django.shortcuts import render
#other imports
from .models import Item,OrderItem
from django.views.generic import ListView,DetailView
from django.contrib.auth.decorators import login_required
# Create your views here.
# def home(request):#get request from server
#     context={
#         'items':Item.objects.all()
#     }
#     return render(request,'home.html',context=context)
#     #we get request for pages

class HomeView(ListView):
    model= Item
    pagination_by = 6 #no. of items on a page
    template_name = 'home.html'

# @login_required(login_url='../accounts/login/')   #login decorater
class ProductDetailView(DetailView):
    model = Item
    template_name = "detail.html"
    
@login_required(login_url='../accounts/login/')   #login decorater
def add_to_cart(request,slug):
    item=get_object_or_404(Item,slug=slug)
    order_item,created=OrderItem.objects.get_object_or_create(item=item,user=request.user,ordered=False)
    orer_q=Order.objects.filter(user=request.user,ordered=False)
    if order_q.exists():
        order=order_q[0]
        if order.items.filter(iter__slug=item.slug).exists():
            order_item +=1
            order_item.save()
            messages.info(request,"Item added to cart")
            return redirect("fronted:summary")
        else:
            messages.info(request,"Item added to cart")
            order.items.add(order_item)
            return redirect("fronted:summary")
    else:
        ordered_date = timezone.now()
        order =Order.objects.create(user=request.user,ordered_date=ordered_date)
        order.items.add(order_item)
        messages.info(request,"Item added to cart")
        return redirect("fronted:summary")
# def testpage(request):
#     return render(request,'test.html')



templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title> {% block title %} {% endblock title %}</title>
        {% comment %} <title>Shop Homepage - Start Bootstrap Template</title> {% endcomment %}
        {% comment %} <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="assets/favicon.ico" /> {% endcomment %}
        <!-- Bootstrap icons-->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet" />
        <!--save css file and edit link by load static Core theme CSS (includes Bootstrap adding style to django )-->
        <link href="{% static 'style.css' %}" rel="stylesheet" />
    </head>
    <body>
        <!-- Navigation-->
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="container px-4 px-lg-5">
                <a class="navbar-brand" href="#!">Start Bootstrap</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0 ms-lg-4">
                        <li class="nav-item"><a class="nav-link active" aria-current="page" href="{% url 'fronted:home' %}">Home</a></li>
                        <li class="nav-item"><a class="nav-link" href="#!">About</a></li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" id="navbarDropdown" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">Shop</a>
                            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <li><a class="dropdown-item" href="#!">All Products</a></li>
                                <li><hr class="dropdown-divider" /></li>
                                <li><a class="dropdown-item" href="#!">Popular Items</a></li>
                                <li><a class="dropdown-item" href="#!">New Arrivals</a></li>
                            </ul>
                        </li>
                    </ul>
                    <form class="d-flex">
                        <button class="btn btn-outline-dark" type="submit">
                            <i class="bi-cart-fill me-1"></i>
                            Cart
                            <span class="badge bg-dark text-white ms-1 rounded-pill">0</span>
                        </button>
                    </form>

                    {% if user.is_authenticated %}
                    <li class="nav-item dropdown d-flex">
                        <a class="nav-link dropdown-toggle" id="nDropDown" href="#" role="button" data-bs-toggle="dropdown">{{user.get_username}}</a>
                        <ul class="dropdown-menu" aria-labelledby="nDropdown">
                            <li><a class="dropdown-item" href=""> My Orders </a></li>
                            <li><hr class="dropdown-divider"/></li>
                            <li><a class="dropdown-item" href="{% url 'accounts:logout' %}"> Sign out</a></li>
                        </ul>
                    </li>
                    {% else %}
                    <li class="nav-item d-flex"><a class="nav-link active" aria-current="page" href="{% url 'accounts:login' %}">Signin/Signup</a></li>
                    {% endif %}
                </div>
            </div>
        </nav>
        <!-- Header-->
        {% comment %} <header class="bg-dark py-5">
            <div class="container px-4 px-lg-5 my-5">
                <div class="text-center text-white">
                    <h1 class="display-4 fw-bolder">Shop in style</h1>
                    <p class="lead fw-normal text-white-50 mb-0">With this shop hompeage template</p>
                </div>
            </div>
        </header> {% endcomment %}
        <!-- Section-->
        {% block content %}

        {% endblock %}
        <!-- Footer-->
        <footer class="py-5 bg-dark">
            <div class="container"><p class="m-0 text-center text-white">Copyright &copy; Ecommerce Django</p></div>
        </footer>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        {% comment %} <script src="js/scripts.js"></script> django can't find this file {% endcomment %}
    </body>
</html>

templates/detail.html
{% extends 'base.html' %}
{% block title %}Ecom |{{object.title}} {% endblock title %}
{% block content %}
<section class="py-5">
    <div class="container px-4 px-lg-5 mt-5">
        <div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-center">
                    <!-- Product details-->
                    <div class="card-body p-4">
                        <div class="text-center">
                            <!-- Product name-->
                            <h5 class="fw-bolder">{{ object.title }}</h5>
                            <!-- Product price-->
                            {% comment %} <p>${{ item.price }}</p>
                            <p>${{ item.discount_price }}</p> {% endcomment %}
                            {% if item.discount_price %}
                            <p><del class="mr-2 text-danger">${{ item.price }}</del>
                            ${{ item.discount_price }}</p>
                            <span class="badge rounded-pill bg-danger">${{item.get_discount_percent|floatformat:2}} off</span>
                            
                            {% else %}
                            <p>${{ item.price }}</p>
                            {% endif %}

                            <span class="badge rounded-pill bg-info">{{item.get_category_display}}</span>
                            <span class="badge rounded-pill bg-info">{{item.get_label_display}}</span>

                            <p>{{item.description}}</p>
                            
                            <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                                <div class="text-center">
                                    <a class="btn btn-outline-dark mt-auto me-4" href="{% url 'fronted:home' %}">Continue Shopping</a>
                                    <a class="btn btn-outline-dark mt-auto" href="">Add to Cart<i class="bi-cart-fill me-1"></i></a>
                                </div>
                            
                            {% comment %} <p> {{item.get_category_display}}</p> {% endcomment %}
                            <p class="btn btn-success btn-sm"> {{item.get_category_display}}</p>
                        </div>
                    </div>
                    <!-- Product actions-->
                    <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                        <div class="text-center"><a class="btn btn-outline-dark mt-auto" href="#">View options</a></div>
                    </div>
                </div>
            </div>
            {% comment %} {% for item in items %} {% endcomment %}
            {% comment %} {% for item in object_list %}
            <div class="col mb-5"> 
                <div class="card shadow h-100">
                    <!-- Product image-->
                    <img class="card-img-top p-2" src="{{item.image.url}}" alt="..." />
                    <!-- Product details-->
                    <div class="card-body p-4">
                        <div class="text-center">
                            <!-- Product name-->
                            <h5 class="fw-bolder">{{ item.title }}</h5>
                            <!-- Product price-->
                            {% comment %} <p>${{ item.price }}</p>
                            <p>${{ item.discount_price }}</p> {% endcomment %}
                            {% comment %} {% if item.discount_price %}
                            <p><del class="mr-2 text-danger">${{ item.price }}</del>
                            ${{ item.discount_price }}</p>
                            <span class="badge rounded-pill bg-danger">${{item.get_discount_percent|floatformat:2}} off</span>
                            
                            {% else %}
                            <p>${{ item.price }}</p>
                            {% endif %} {% endcomment %}
                            
                            {% comment %} <span class="badge badge-pill">{{Item.category}} </span> {% endcomment %}
                            {% comment %} <p> {{item.get_category_display}}</p> {% endcomment %}
                            {% comment %} <p class="btn btn-success btn-sm"> {{item.get_category_display}}</p>
                        </div>
                    </div>
                    <!-- Product actions-->
                    <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                        <div class="text-center"><a class="btn btn-outline-dark mt-auto" href="#">View options</a></div>
                    </div>
                </div>
            </div> {% endcomment %}
            {% comment %} {% endfor %} {% endcomment %}
        </div>
    </div>
</section>
{% endblock %}

templates/home.html
{% extends 'base.html' %}
{% block title %}Ecom Home {% endblock title %}
{% block content %}
<section class="py-5">
    <div class="container px-4 px-lg-5 mt-5">
        <div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-center">
            {% comment %} {% for item in items %} {% endcomment %}
            {% for item in object_list %}
            <div class="col mb-5"> 
                <div class="card shadow h-100">
                    <!-- Product image-->
                    <img class="card-img-top p-2" src="{{item.image.url}}" alt="..." />
                    <!-- Product details-->
                    <div class="card-body p-4">
                        <div class="text-center">
                            <!-- Product name-->
                            <h5 class="fw-bolder">{{ item.title }}</h5>
                            <!-- Product price-->
                            {% comment %} <p>${{ item.price }}</p>
                            <p>${{ item.discount_price }}</p> {% endcomment %}
                            {% if item.discount_price %}
                            <p><del class="mr-2 text-danger">${{ item.price }}</del>
                            ${{ item.discount_price }}</p>
                            <span class="badge rounded-pill bg-danger">${{item.get_discount_percent|floatformat:2}} off</span>
                            
                            {% else %}
                            <p>${{ item.price }}</p>
                            {% endif %}
                            
                            {% comment %} <span class="badge badge-pill">{{Item.category}} </span> {% endcomment %}
                            {% comment %} <p> {{item.get_category_display}}</p> {% endcomment %}
                            <p class="btn btn-success btn-sm"> {{item.get_category_display}}</p>
                        </div>
                    </div>
                    <!-- Product actions-->
                    <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                        <div class="text-center"><a class="btn btn-outline-dark mt-auto" href="{{item.get_item_url}}">View options</a></div>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</section>
{% endblock %}

templates/login.html
{% extends 'base.html' %}
{% load static %}
{% block siteTitle %} Login {% endblock %}

{% block content %}

<div class="container">
    <form method="post">
        {% csrf_token %}
        {{signin_form}}
        <button class="btn btn-info" type="submit">Sign in</button>
    </form>
    <p> Please <a href="{% url 'accounts:signup' %}">Sign up</a>for an account</p>
</div>
{% endblock %}

templates/signup.html
{% extends 'base.html' %}
{% load static %}
{% block siteTitle %} Sign up {% endblock %}

{% block content %}

<div class="container">
    <form method="post">
        {% csrf_token %}
        {{form}}
        <button type="submit" class="btn btn-info">Sign up</button>
    </form>
</div>
{% endblock %}
{% comment %} {% extends 'base.html' %}
{% block title %} Sign Up {% endblock %}
{% block content %}
<div class="container mb-5 mt-5">
    <form method="post">
        {% csrf_token %}
        {{form}}
        <button type="submit" class="btn btn-info">Sign up</button>
    </form>
</div>
{% endblock content %} {% endcomment %}

templates/summary.html
{% extends 'base.html' %}
{% block title %} Ecom | Summary {% endblock title %}
{% block content %}
<section class="py-5">
    <div class="container px-4 px-lg-5 mt-5">
        <div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-center">
            <div class="col-md-8 mb-5">

            </div>

            <div class="col-md-8 mb-5">

            </div>
        </div>
    </div>
</section>
{% endblock %}

templates/test.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>This is a test</title>
    </head>
    <body>
        This is a test
    </body>
    </html>